management:
  endpoints:
    beans:
      enabled: false
    web:
      base-path: /management
      exposure:
        include: "*"
  endpoint:
    health:
      sensitive: false
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false
  metrics:
    enabled: false

spring:
  application:
    name: queryfier
  profiles:
    active: #spring.profiles.active#
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: HTML
  mail:
    host: smtp.gmail.com
    port: 587
    username: alpha9ineinc@gmail.com
    password: dligfaajruiqfzif
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: false
  messages:
    basename: i18n/messages
  jpa:
    show-sql: true


info:
  project:
    version: #project.version#